#' Elements composing a Frequency Table
#'
#' Generates a list with the elements composing your Frequency table generated by the freqTab_quantitative() and freqTab_categorical() functions. It is also used to calculate measures of central tendency.
#' WARNING: It is important to note, that data columns that has 0 as its min() will not function.
#'
#' @param datasetColumn From a cleansed dataset column, such as: diamonds$price
#'
#' @return A list with number of observations, classes according to Sturges formula, amplitude of every class and limits of every group
#' @export
#'
#' @examples diamonds <- ggplot2::diamonds
#' freqTab_elements(diamonds$price)
freqTab_elements <-
  function(datasetColumn){
    column2Table <- na.omit(as.numeric(datasetColumn))
    n <- length(column2Table)
    c <- round(log2(n) + 1)
    amplitude <- round((range(column2Table)[2] - range(column2Table)[1]) / c, )
    groupLimits <- c(seq(from = min(column2Table), to = max(column2Table) + amplitude, by = amplitude))

    elements <- list(n, c, amplitude, groupLimits)
    return(elements)
  }
