#' Median for grouped data
#'
#' A function which calculates the Median for grouped data. It uses the table generated by freqTab_categorical() or freqTab_quantitative().
#'
#' @param datasetColumn From the original cleansed dataset column, such as: cars$speed
#' @param freqTable.Freq Frequency column from the table generated by freqTab functions. E.g.: diamonds$Freq
#' @param freqTable.Acc.Freq Accumulated Frequency column from the table generated by freqTab functions. E.g.: diamonds$Acc.Freq
#' @param round Boolean operator that indicates whether the Median is rounded or not. Default is TRUE.
#' @param digits Digits for the Median  to be rounded with the round() function. Default at the round() default being 0 for a whole number.
#'
#' @return Median from the grouped data.
#' @export
#'
#' @examples diamonds <- ggplot2::diamonds
#' price <- freqTab_quantitative(diamonds$price, "price", 10)
#' median_price <- median_freqTab(diamonds$price, price$Freq, price$Acc.Freq)
#' median_price
median_freqTab <-
function(datasetColumn, freqTable.Freq, freqTable.Acc.Freq, round = T, digits){
    elements <- freqTab_elements(datasetColumn)

    if(as.numeric(elements[1]) %% 2){
      n <- as.numeric(elements[1]) / 2
    }else{
      n <- as.numeric(elements[1]) / 2 + 1
    }

    medianIndex <- which(freqTable.Acc.Freq >= n)[1]
    freqMedianClass <- freqTable.Freq[medianIndex]
    prev.AccFreqMedianClass <- freqTable.Acc.Freq[medianIndex - 1]

    if(length(prev.AccFreqMedianClass) == 0){
      prev.AccFreqMedianClass = 0
    }

    median <- as.numeric(elements[[c(4, medianIndex)]]) + (((n - prev.AccFreqMedianClass) / freqMedianClass) * as.numeric(elements[2]))
    if(round == T){
      round(median, digits)
    }else{
      return(median)
    }
  }
