#' Mode for grouped data
#'
#' A function which calculates the Mode for grouped data. It uses the table generated by freqTab_categorical() or freqTab_quantitative().
#'
#' @param datasetColumn From a cleansed dataset column, such as: diamonds$price
#' @param freqTable.Freq Frequency column from the table generated by freqTab functions. E.g.: diamonds$Freq
#' @param round Boolean operator that indicates whether the Median is rounded or not. Default is TRUE.
#' @param digits Digits for the Median  to be rounded with the round() function. Default at the round() default being 0 for a whole number.
#'
#' @return Returns the Mode as integer.
#' @export
#'
#' @examples diamonds <- ggplot2::diamonds
#' price <- freqTab_quantitative(diamonds$price, "price", 10)
#' mode_price <- mode_freqTab(diamonds$price, price$Freq)
#' mode_price
mode_freqTab <-
  function(datasetColumn, freqTable.Freq, round = T, digits){
    indexModalClass <- which(freqTable.Freq == max(freqTable.Freq))
    freqModalClass <- freqTable.Freq[indexModalClass]
    prev.freqModalClass <- freqTable.Freq[indexModalClass - 1]
    post.freqModalClass <- freqTable.Freq[indexModalClass + 1]

    if(length(prev.freqModalClass) == 0){
      prev.freqModalClass = 0
    }
    if(is.na(post.freqModalClass) == T){
      post.freqModalClass = 0
    }

    elements <- freqTab_elements(datasetColumn)

    mode <- as.numeric(elements[[c(4, indexModalClass)]]) + ((freqModalClass - prev.freqModalClass) / ((freqModalClass - prev.freqModalClass) + (freqModalClass - post.freqModalClass)) * as.numeric(elements[3]))
    if(round == T){
      round(mode, digits)
    }else{
      return(mode)
    }
  }
